### ISSUE TITLE
并没有什么效果

### ISSUE THREAD

**Issue by yaphet266** [yangzhongke/Zack.DotNetTrimmer#10]

**Comment by yangzhongke** [comment]
谢谢你的反馈。
请提供重现问题的项目。

**Comment by yaphet266** [comment]
杨老师好，我刚创建了一个.net 6的项目，用”dotnet publish -c Release -r win-x64 /p:PublishSingleFile=true -o ./publish“命令发布，执行后信息如下：
G:\temp\0310\windowsx64>Zack.DotNetTrimmer.exe G:\temp\0310\windowsx64\ASPNETCore6WebAPI1.exe
Press Ctrl+C or Ctrl+Break to terminate the application to be trimmed.
done, reduced file size:0.00 MB
Waiting for exit.
Trimming done.
Original files have been backup into C:\Users\Yaphet\Documents\ASPNETCore6WebAPI1\Backup20220310113421

**Comment by yangzhongke** [comment]
文档里说了，不要用“PublishSingleFile=true”
![image](https://user-images.githubusercontent.com/13821363/157584101-184f4357-c5e2-4317-acc1-8ab0b2dbabc3.png)

**Comment by yaphet266** [comment]
确实可以，裁剪后的文件能否再合并成一个单文件，因为变单文件前是90多MB,单文件80多MB,裁剪后70多MB。再变成单文件是不是可以更小。

**Comment by yangzhongke** [comment]
是的，这个我需要再去研究。
你可以先用压缩软件打包。
