### ISSUE TITLE
裁剪后，程序直接不能用了

### ISSUE THREAD

**Issue by toolgood** [yangzhongke/Zack.DotNetTrimmer#12]
裁剪后，程序直接不能用了 

https://github.com/toolgood/DevTest

**Comment by toolgood** [comment]
并且 不能支持 单个文件的应用程序 进行裁剪

**Comment by yangzhongke** [comment]
你好，我用您的程序测试了一下，剪裁后没问题。
原始153MB，裁剪后54MB
![image](https://user-images.githubusercontent.com/13821363/157786560-dcc3ef30-7edd-43fb-a773-ffbee89681ff.png)

这是我的发布选项
![image](https://user-images.githubusercontent.com/13821363/157786688-86105031-8409-410c-a6be-4aec80363e5e.png)
请核实，如果还不行。请提供您的发布选项。

由于‘生成单个文件“很难去提取单个的程序集以及进行合并（毕竟还要考虑支持多个操作系统的二进制可执行程序），所以不准备支持“生成单个文件”
