### ISSUE TITLE
找不到指定文件 System.Private.Uri

### ISSUE THREAD

**Issue by windfgg** [yangzhongke/Zack.DotNetTrimmer#16]
## 错误
![image](https://user-images.githubusercontent.com/87279659/163386059-538bb90a-3152-48a8-926f-be7a837cbe5a.png)
![image](https://user-images.githubusercontent.com/87279659/163386220-c7659d92-204f-4b2b-b0f7-f33919eb309a.png)

## 发布配置
![image](https://user-images.githubusercontent.com/87279659/163386270-c72bf71d-0d0f-4748-b227-0daa0b909788.png)
## 环境
.NET6 经检查目录下并没有System.Private.Uri.dll 文件

**Comment by yangzhongke** [comment]
请把可以重现问题的程序（如果担心泄密，可以只发布二进制程序）发给我，可以传到网盘或者放到github上。

**Comment by windfgg** [comment]
https://github.com/WindFgg/TestPuppeteerSharp

名称为OneOuchn的控制台应用

**Comment by yangzhongke** [comment]
抱歉，使用你的代码发布后没有重现错误。
我这里运行正常
![image](https://user-images.githubusercontent.com/13821363/163962105-3e5c648f-4451-4102-b04c-ae2be69abd7b.png)

因为我不清楚你的软件怎么用，所以也可能是测试步骤错误。您可以给出软件的操作说明、配置文件等并且给出发布后的二进制沉痼
