### ISSUE TITLE
 Could not find file 'C:\Users\zhang\Documents\TMCADMgr\Backup\Accessibility.dll'.

### ISSUE THREAD

**Issue by zhang151412** [yangzhongke/Zack.DotNetTrimmer#18]
杨老师，一开始报错找不到路径，我把报错信息的路径建好后，又报错找不到文件……
管理员模式也不行

**Comment by zhang151412** [comment]
![image](https://user-images.githubusercontent.com/2377938/222994278-e4715204-cecb-489d-96d0-2b57fa25254d.png)

**Comment by yangzhongke** [comment]
你把被精简的程序复制到D盘试试呢？

**Comment by zhang151412** [comment]
抱歉杨老师，最近没上来GitHub，被精简的程序就是放在D盘的。。。。

**Comment by yangzhongke** [comment]
这里显示的是C盘，你是放到D盘试了，也不行？
![image](https://user-images.githubusercontent.com/13821363/224829330-81219777-012c-4710-b3c4-c74f1274f171.png)
