### ISSUE TITLE
为什么会提示“Entering Direct Mode”？

### ISSUE THREAD

**Issue by LowerAI** [yangzhongke/Zack.DotNetTrimmer#19]
执行命令后如下图
![image](https://github.com/yangzhongke/Zack.DotNetTrimmer/assets/4626237/274a5ef0-830b-4a7d-9337-69c6f3927237)

跟没裁剪一样，请问是因为发布时已经裁剪到极致，没法更进一步吗

**Comment by yangzhongke** [comment]
对
