### ISSUE TITLE
请问支持.net core 3.1 吗 我在使用过程中卡住不再往下执行

### ISSUE THREAD

**Issue by dudylan** [yangzhongke/Zack.DotNetTrimmer#20]
![image](https://github.com/yangzhongke/Zack.DotNetTrimmer/assets/34180156/ae950991-ed79-419c-a488-580b25ee0d27)

**Comment by yangzhongke** [comment]
After completing all functions, press Ctrl+C or Ctrl+Break in the Zack.DotNetTrimmer console to send a shutdown request for the program to be trimmed.
