### ISSUE TITLE
请问支持裁剪.net8的winform项目吗

### ISSUE THREAD

**Issue by Alex1911-Jiang** [yangzhongke/Zack.DotNetTrimmer#22]
目标框架 net8.0-windows7.0
部署模式 独立
目标运行时 win-x64
勾选了生成单个文件
（以及勾选和未勾选 启用 ReadyToRun 编译都试过，都不行）

输出 
Version:2.0.0.2(Microsoft Windows NT 10.0.19043.0)
Error: Only self-contained applications are supported, and framework-dependent ones aren't."

**Comment by yangzhongke** [comment]
抱歉，不支持“生成单个文件”。文档中有说明：
![image](https://github.com/yangzhongke/Zack.DotNetTrimmer/assets/13821363/4080540b-6dc5-48a9-b6a2-7995f71892f9)
