### ISSUE TITLE
Deletion of *.deps.json and *.runtimeconfig.json prevents use of nBeauty2

### ISSUE THREAD

**Issue by elmkni** [yangzhongke/Zack.DotNetTrimmer#25]
Hi, Zack!

My name is Elmar and I've just tested Your [DotNetTrimmer](https://github.com/yangzhongke/Zack.DotNetTrimmer) program.

It's fantastic -- it reduced the overall size of a WinForms C# program, 
that was already trimmed with `<PublishTrimmed>`, even further!

But there's one little problem: 

I would like to bring my program into a nicer directory structure like:
```
├── MyApp (dir)  
│    ├── net9runtime (dir with necessary *.dll runtime files)
│    ├── hostfxr.dll
│    ├── hostpolicy.dll
│    ├── MyApp.deps.json
│    ├── MyApp.dll
│    └── MyApp.runtimeconfig.json
│
└── MyApp.exe
```
For this task I intend to make use of the very good program [nBeauty2](https://github.com/nulastudio/NetBeauty2).

To make [nBeauty2](https://github.com/nulastudio/NetBeauty2) work the two config files:

- **MyApp.deps.json** (_with all zack-deleted *.dll entries removed!_)  +
- **MyApp.runtimeconfig.json** 

are needed!

I had to restore them manually, including laboriously removing all 
occurences of zack-deleted assemblies, because [DotNetTrimmer](https://github.com/yangzhongke/Zack.DotNetTrimmer)
had deleted these important files instead of applying the needed 
changes to them!

Of course I know they are not strictly needed to run MyApp.exe 
when all runtime files stay in the same directory with the main 
executable, but [nBeauty2](https://github.com/nulastudio/NetBeauty2) needs them to apply its alterations!

Now I would kindly ask:

if it might be possible to change the behaviour of [DotNetTmmer](https://github.com/yangzhongke/Zack.DotNetTrimmer) 
to instead of deleting these files, to alter them according to the 
applied trimming action and to remove the entries of deleted 
assemblies from the MyApp.deps.json file, in order to keep the 
application working with the config files in the same directory.

Such a change to [DotNetTmmer](https://github.com/yangzhongke/Zack.DotNetTrimmer) would be much appreciated,
not only by myself, but (I'm shure) also by many other users  of 
your **_brilliant program_**!

With best regards,

Elmar

**Comment by yangzhongke** [comment]
Hi. In different .net versions, *.json files have differnt schema, so it's a tough work to write a tool to fine-grainedly modify them. Sorry for not having effort to change it.
A workround would be writing a script to backup those *.json files before running Zack.DotNetTrimmer, and then restore them after that.
